import { ProductInterface } from "./types";

export const products: ProductInterface[] = [
    {
      id: "1a2b3c4d-1a2b-1a2b-1a2b-1a2b3c4d5e6f",
      name: "Smartphone X100",
      category: "Electronics",
      cost: 500,
      finalPrice: 650,
      discount: 10,
      profitPercentage: 30,
      stock: 50,
      allowNegativeStock: false,
      trackStock: true,
      minimumStock: 10,
      enabled: true,
      notesDescription: "Latest model with advanced features",
      taxes: 15,
      barcode: "1234567890123",
    },
    {
      id: "2b3c4d5e-2b3c-2b3c-2b3c-2b3c4d5e6f7g",
      name: "Laptop Pro 15",
      category: "Computers",
      cost: 1200,
      finalPrice: 1500,
      discount: 5,
      profitPercentage: 25,
      stock: 20,
      allowNegativeStock: false,
      trackStock: true,
      minimumStock: 5,
      enabled: true,
      notesDescription: "High-performance laptop for professionals",
      taxes: 18,
      barcode: "2345678901234",
    },
    {
      id: "3c4d5e6f-3c4d-3c4d-3c4d-3c4d5e6f7g8h",
      name: "Wireless Headphones",
      category: "Audio",
      cost: 100,
      finalPrice: 150,
      discount: 15,
      profitPercentage: 35,
      stock: 100,
      allowNegativeStock: true,
      trackStock: true,
      minimumStock: 20,
      enabled: true,
      notesDescription: "Noise-canceling wireless headphones",
      taxes: 10,
      barcode: "3456789012345",
    },
    {
      id: "4d5e6f7g-4d5e-4d5e-4d5e-4d5e6f7g8h9i",
      name: "Smartwatch Series 5",
      category: "Wearables",
      cost: 200,
      finalPrice: 300,
      discount: 20,
      profitPercentage: 40,
      stock: 75,
      allowNegativeStock: true,
      trackStock: true,
      minimumStock: 15,
      enabled: true,
      notesDescription: "Water-resistant smartwatch with GPS",
      taxes: 12,
      barcode: "4567890123456",
    },
    {
      id: "5e6f7g8h-5e6f-5e6f-5e6f-5e6f7g8h9i0j",
      name: "Bluetooth Speaker",
      category: "Audio",
      cost: 50,
      finalPrice: 80,
      discount: 10,
      profitPercentage: 30,
      stock: 150,
      allowNegativeStock: true,
      trackStock: true,
      minimumStock: 30,
      enabled: true,
      notesDescription: "Portable speaker with high-quality sound",
      taxes: 8,
      barcode: "5678901234567",
    },
  ];
  